# Generated by Django 3.2 on 2021-06-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_invoice_number', models.CharField(max_length=100)),
                ('supplier_invoice_date', models.DateField(default='')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_state', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField(default=0)),
                ('narration', models.CharField(default='', max_length=100)),
                ('user_user_id', models.CharField(default='', max_length=100)),
                ('manager_user_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='invoice_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100)),
                ('basic_amount', models.IntegerField(default=0)),
                ('gst_rate', models.IntegerField(default=0)),
                ('cgst', models.IntegerField(default=0)),
                ('sgst', models.IntegerField(default=0)),
                ('igst', models.IntegerField(default=0)),
            ],
        ),
    ]
